config/routes.rb
Rails.application.routes.draw do
  resources :tea_items

  get 'teas/featured', to: 'tea_items#featured'
  get 'teas/:id', to: 'tea_items#show'
  get 'teas', to: 'tea_items#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tea_item.rb
class TeaItem < ApplicationRecord

  self.inheritance_column = :_type_disabled

  TYPE_OPTIONS     = ['1','2','3']

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tea_items_controller.rb
class TeaItemsController < ApplicationController

  before_action :set_default_response_format


  # GET /tea_items
  # GET /tea_items.json
  def index
    @tea_items = TeaItem.all
  end


  # GET /tea_items/featured
  # GET /tea_items/featured.json
  def featured
    @tea_items = TeaItem.where('price > ?', 50)
  end

  # GET /tea_items/1
  # GET /tea_items/1.json
  def show
    @tea_item = TeaItem.find(params[:id])
  end


  private

    def set_default_response_format
      request.format = :json
    end

end

app/controllers/tea_items_controller_backup.rb
# class TeaItemsController < ApplicationController
#
#
#
#
#   before_action :set_tea_item, only: [:show, :edit, :update, :destroy]
#
#
#     # respond_to    :json
#
#   # GET /tea_items
#   # GET /tea_items.json
#   def index
#     @tea_items = TeaItem.all
#   end
#
#
#   # GET /tea_items/featured
#   # GET /tea_items/featured.json
#   def featured
#     @tea_items = TeaItem.where('price > ?', 50)
#   end
#
#   # GET /tea_items/1
#   # GET /tea_items/1.json
#   def show
#   end
#
#   # GET /tea_items/new
#   def new
#     @tea_item = TeaItem.new
#   end
#
#   # GET /tea_items/1/edit
#   def edit
#   end
#
#   # POST /tea_items
#   # POST /tea_items.json
#   def create
#     @tea_item = TeaItem.new(tea_item_params)
#
#     respond_to do |format|
#       if @tea_item.save
#         format.html { redirect_to @tea_item, notice: 'Tea item was successfully created.' }
#         format.json { render :show, status: :created, location: @tea_item }
#       else
#         format.html { render :new }
#         format.json { render json: @tea_item.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # PATCH/PUT /tea_items/1
#   # PATCH/PUT /tea_items/1.json
#   def update
#     respond_to do |format|
#       if @tea_item.update(tea_item_params)
#         format.html { redirect_to @tea_item, notice: 'Tea item was successfully updated.' }
#         format.json { render :show, status: :ok, location: @tea_item }
#       else
#         format.html { render :edit }
#         format.json { render json: @tea_item.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # DELETE /tea_items/1
#   # DELETE /tea_items/1.json
#   def destroy
#     @tea_item.destroy
#     respond_to do |format|
#       format.html { redirect_to tea_items_url, notice: 'Tea item was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end
#
#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_tea_item
#       @tea_item = TeaItem.find(params[:id])
#     end
#
#     # Never trust parameters from the scary internet, only allow the white list through.
#     def tea_item_params
#       params.require(:tea_item).permit(:name, :description, :image, :link, :price, :type)
#     end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tea_items_helper.rb
module TeaItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tea</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tea_items/_form.html.erb
<%= form_for(tea_item) do |f| %>
  <% if tea_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tea_item.errors.count, "error") %> prohibited this tea_item from being saved:</h2>

      <ul>
      <% tea_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tea_items/edit.html.erb
<h1>Editing Tea Item</h1>

<%= render 'form', tea_item: @tea_item %>

<%= link_to 'Show', @tea_item %> |
<%= link_to 'Back', tea_items_path %>

app/views/tea_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tea Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Link</th>
      <th>Price</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tea_items.each do |tea_item| %>
      <tr>
        <td><%= tea_item.name %></td>
        <td><%= tea_item.description %></td>
        <td><%= tea_item.image %></td>
        <td><%= tea_item.link %></td>
        <td><%= tea_item.price %></td>
        <td><%= tea_item.type %></td>
        <td><%= link_to 'Show', tea_item %></td>
        <td><%= link_to 'Edit', edit_tea_item_path(tea_item) %></td>
        <td><%= link_to 'Destroy', tea_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tea Item', new_tea_item_path %>

app/views/tea_items/new.html.erb
<h1>New Tea Item</h1>

<%= render 'form', tea_item: @tea_item %>

<%= link_to 'Back', tea_items_path %>

app/views/tea_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tea_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tea_item.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @tea_item.image %>
</p>

<p>
  <strong>Link:</strong>
  <%= @tea_item.link %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tea_item.price %>
</p>

<p>
  <strong>Type:</strong>
  <%= @tea_item.type %>
</p>

<%= link_to 'Edit', edit_tea_item_path(@tea_item) %> |
<%= link_to 'Back', tea_items_path %>